# Generated by Django 5.1.2 on 2024-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(related_name='restaurants', to='orders.category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='operating_hours',
            field=models.CharField(max_length=100),
        ),
    ]
