# Generated by Django 5.1.2 on 2024-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_restaurant_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
