# Generated by Django 5.1.2 on 2024-10-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_restaurant_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
    ]
