# Generated by Django 5.1.2 on 2024-11-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_optiongroup_optionitem_menu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
    ]
