# Generated by Django 5.1.2 on 2024-11-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_menu_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='orders.menu'),
        ),
    ]
