# Generated by Django 5.1.2 on 2024-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChart',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('menu_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '주문 접수'), ('delivering', '배달 중'), ('delivered', '배달 완료'), ('canceled', '주문 취소')], max_length=20),
        ),
    ]
