# Generated by Django 5.1.2 on 2024-11-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderchart_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '주문 완료'), ('accepted', '주문 수락'), ('delivering', '배달 중'), ('delivered', '배달 완료'), ('canceled', '주문 취소')], max_length=20),
        ),
    ]
