# Generated by Django 5.1.2 on 2024-11-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_rider_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('moving', '이동 중')], max_length=100)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.rider')),
            ],
        ),
    ]
