# Generated by Django 5.1.2 on 2024-12-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_final_price_order_user_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.restaurant'),
        ),
    ]
