# Generated by Django 5.1.2 on 2025-01-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_discount_amount_usercoupon_used_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
    ]
